[package]
name = "pest_fmt"
version = "0.1.2"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/GalAster/pest-fmt"
license = "MPL-2.0"

[dependencies]
pest = "2.1.2"
textwrap = "0.11"
walkdir = "2"
toml = "0.5"

[dev-dependencies]
pest_generator = "2.1.2"
quote = "1.0"
